import AnimatedText from "@/components/AnimatedText"
import Benefits from "@/components/Benefits"
import CallToAction from "@/components/CallToAction"
import Documents from "@/components/Documents"
import ExtraServices from "@/components/ExtraServices"
import Faq from "@/components/Faq"
import Hero from "@/components/Hero"
import Footer from "@/components/Layout/Footer"
import Process from "@/components/Process"
import Services from "@/components/Services"
import {
  Bounds,
  Environment,
  OrbitControls,
  Preload,
  View,
} from "@react-three/drei"
import { Canvas, useFrame } from "@react-three/fiber"
import Head from "next/head"
import { Suspense, useRef } from "react"

/////////////////
//
// TESTA DENNA COOLA
//
// https://sketchfab.com/3d-models/neon-stage-6037d87967fc4acf8e8ba1de875dc743
//
// https://sketchfab.com/3d-models/free-skybox-dystopian-alleyway-80ddc539289a4a439c0e3ea4e59e2b84
////////////////////

export function Lighting() {
  return (
    <>
      <Environment preset="city" />
      <ambientLight intensity={1} />
    </>
  )
}

function Box() {
  const ref = useRef()

  useFrame((state, delta) => {
    ref.current.rotation.y += 0.01
  })
  return (
    <mesh ref={ref} visible={false}>
      <boxGeometry />
      <meshStandardMaterial color="blue" />
    </mesh>
  )
}

export const interpolateFunc = (t) => 1 - Math.exp(-5 * t) + 0.007 * t // Matches the default Bounds behavior

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero
        title="Mobilitet & parkeringsutredningar"
        carousel={["fast enkelt", "fast snabbt", "fast kul"]}
      />

      <section>
        <div className="row">
          <h2>
            <AnimatedText
              text="Att göra parkeringsutredningar tar tid, kostar mycket och kräver
              onödig ansträngning. Oorganiserad data och otydliga processer
              skapar kaos istället för resultat."
            />
          </h2>
        </div>
      </section>

      <Documents />

      <Services title="Våra tjänster" />

      <ExtraServices title="Andra tjänster & tillval" />

      <Benefits title="Fördelar med Parkyria" />

      {/* <View style={{ width: "100%", height: "100vh" }}>
            <Lighting />

            <Sparkles
              count={100}
              scale={10}
              size={5}
              opacity={1}
              speed={5}
              color="blue"
            />

            <color attach="background" args={["black"]} />

            <Rotate position={[0, 0, -0.5]}>
              <mesh>
                <meshStandardMaterial color="blue" />
                <boxGeometry />
              </mesh>
            </Rotate>
          </View> */}

      {/* <div style={{ height: "400vh", position: "relative" }}>
            <View
              style={{
                width: "100%",
                height: "100vh",
                position: "sticky",
                top: 0,
              }}
            >
              <Lighting />

              <Sparkles
                count={100}
                scale={10}
                size={5}
                opacity={1}
                speed={5}
                color="white"
              />

              <color attach="background" args={["black"]} />

              <Rotate position={[0, 0, -0.5]}>
                <mesh>
                  <meshStandardMaterial color="white" />
                  <boxGeometry />
                </mesh>
              </Rotate>
            </View>
          </div> */}

      <Process
        title="Vår (enkla) process"
        text="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna."
      />

      <Faq
        title="FAQ"
        text="Här besvarar vi några av våra vanligaste frågor."
      />

      <Footer />

      <div
        style={{
          position: "fixed",
          top: 0,
          left: 0,
          width: "100%",
          height: "100%",
          zIndex: "-1",
        }}
      >
        <Canvas>
          <OrbitControls />
          <Lighting />

          {/* <Bounds
            fit
            clip
            observe
            margin={1.5}
            maxDuration={1}
            interpolateFunc={interpolateFunc}
          >
            <Box />
          </Bounds> */}

          <Preload all />
          <View.Port />
          {/* <mesh>
              <meshStandardMaterial color="red" />
              <boxGeometry />
            </mesh> */}
        </Canvas>
      </div>
    </>
  )
}
